### ISSUE TITLE
Question related to HS API

### ISSUE THREAD

**Issue by jrosebr1** [Py-Image/dpd-helpscout-wordpress#2]
According to HelpScout, they will be releasing the MailBox API 2.0 and deprecating the legacy API:

![api](https://user-images.githubusercontent.com/759645/45596953-4fcd0480-b992-11e8-9115-e5ef71451586.png)

Will deprecating the old API effect either (1) this plugin or (2) our Drip tags plugin?

**Comment by d4mation** [comment]
Can you link me to these API Changes? I don't think it would affect us as we aren't using API Keys for them at all, but I'd like to give it a once over to be sure.

**Comment by jrosebr1** [comment]
Sure:

https://developer.helpscout.com/mailbox-api/

**Comment by d4mation** [comment]
Looks like this won't effect any of the integrations that we've built :+1:

We don't directly use the HelpScout API in anything we've built, but rather only use the HelpScout Data related to that Ticket that gets passed over to WP. So these changes won't be an issue for us.

**Comment by jrosebr1** [comment]
Awesome, thanks for the clarification Eric :-)
